- name: deploy grub config
  template:
    src: grub.j2
    dest: /etc/default/grub
    mode: 0644
  notify: update grub

- name: deploy grub password
  template:
    src: 50_password.j2
    dest: /etc/grub.d/50_password
    mode: 0700
  notify: update grub
  when: bootloader_grub_password_protected

- name: remove grub password
  file:
    path: /etc/grub.d/50_password
    state: absent
  notify: update grub
  when: not bootloader_grub_password_protected
