- name: deploy grub config
  template:
    src: grub.j2
    dest: /etc/default/grub
    mode: 0644
  notify: update grub

- name: temporary fix /etc/grub.d/10_linux
  template:
    src: 10_linux_temporary_fix_bionic
    dest: /etc/grub.d/10_linux
    mode: '0755'
  when: bootloader_grub_password_protected and ansible_distribution_release == 'bionic'

- name: make grub entries unrestricted
  lineinfile:
    path: /etc/grub.d/10_linux
    regexp: '^CLASS='
    line: 'CLASS="--class gnu-linux --class gnu --class os --unrestricted"'
  when: bootloader_grub_password_protected and ansible_distribution_release != 'xenial'

- name: deploy grub password
  template:
    src: 50_password.j2
    dest: /etc/grub.d/50_password
    mode: 0700
  notify: update grub
  no_log: True
  when: bootloader_grub_password_protected

- name: remove grub password
  file:
    path: /etc/grub.d/50_password
    state: absent
  notify: update grub
  when: not bootloader_grub_password_protected
