- name: deploy grub config
  template:
    src: grub.j2
    dest: /etc/default/grub
    mode: '0644'
  notify: update grub

- name: make grub entries unrestricted
  lineinfile:
    path: /etc/grub.d/10_linux
    regexp: '^CLASS='
    # TODO: adapt to append the additional option to value already present in file
    line: 'CLASS="--class gnu-linux --class gnu --class os --unrestricted"'
  # TODO: add task or modify to revert change from this task when bootloader_grub_password_protected is False
  when: bootloader_grub_password_protected

- name: deploy grub password
  template:
    src: 50_password.j2
    dest: /etc/grub.d/50_password
    mode: '0700'
  notify: update grub
  no_log: True
  when: bootloader_grub_password_protected

- name: remove grub password
  file:
    path: /etc/grub.d/50_password
    state: absent
  notify: update grub
  when: not bootloader_grub_password_protected
